### ISSUE TITLE
element jumping to the right when scrolling

### ISSUE THREAD

**Issue by FractalFragger** [stefangabos/Zebra_Pin#8]
element jumping to the right when scrolling, when initiated on scroll the whole element moved over to the right about 10 pixels

**Comment by stefangabos** [comment]
can you please show me some code so i can reproduce it? thanks!

**Comment by FractalFragger** [comment]
```
new $.Zebra_Pin($('.sticky-menu'), {
        top_spacing: 0
    });
```

```
<div class="grid-container">
<div class="grid-x grid-margin-x">
<div class="cell small-12 medium-8">
CONTENT HERE
</div>
<div class="cell small-12 medium-4">
<div class="sticky-menu">
SDIEBAR HERE
</div>
</div>
</div>
</div>
```

**Comment by stefangabos** [comment]
this is bootstrap 4, right?

**Comment by FractalFragger** [comment]
no, its Zurb foundation 6.5.1

**Comment by stefangabos** [comment]
oh, ok

**Comment by stefangabos** [comment]
Here's a [quick jsfiddle](https://jsfiddle.net/95f4zd1q/) i've set up. I am not familiar with Foundation so I don't know if there's more CSS to include. Feel free to modify that until you can reproduce the issue. 
I looked on Chrome, by the way

**Comment by FractalFragger** [comment]
i have tried on chrome, firefox, opera, edge and IE and its the same on them all. The code you have is the same as mine except for the jquery version i was on 3.2.1 but i just changed to 3.3.1 but its the same as i scroll when the "sticky" aspect starts it moves over to the right?

**Comment by stefangabos** [comment]
in the jsfiddle i sent it doesn't move for me in Chrome, Firefox and Edge

**Comment by FractalFragger** [comment]
yeah, i noticed, but i cannot see what is doing this. I have turned it off for now until i can properly debug.
