### ISSUE TITLE
Add scroller to element if it reaches certain height

### ISSUE THREAD

**Issue by tmblog** [stefangabos/Zebra_Pin#9]
Hi is it possible to add a scroller to the element that is being stuck once it becomes a certain height. I am using it to stick a sidebar shopping cart so new items get added dynamically and it is changing the height dynamically.

**Comment by stefangabos** [comment]
That's something that is done from CSS. You give your cart a `min-height` and an `overflow-y:auto`. Once its heights is more than the min-height the scrollbar will appear
